### ISSUE TITLE
New Folder Structure

### ISSUE THREAD

**Issue by lionfish0** [SheffieldMLtracking/bee_track#13]
Need bee_track to follow the folder structure in [the readme](https://github.com/SheffieldMLtracking/).

- For this you will need the 'session' id (see suggestion [here](https://github.com/SheffieldMLtracking/bee_track/issues/12) about how to get that from the label).
- Need to update how filename is created etc [here](https://github.com/SheffieldMLtracking/bee_track/blob/0f96572567c2d3423c0f668fa1baeffd77f2fb82/bee_track/camera.py#L196).

**Comment by lionfish0** [comment]
Can you merge it in to main? I'm worried that my tidying will be so
substantial that future merges will be a problem.

**Comment by Aplefen1** [comment]
Coolio merged
